AirportTracker/Models/Aircraft.cs
using System.ComponentModel.DataAnnotations;

namespace AirportTracker.Models
{
    public class Aircraft
    {
        [Key]
        public int AircraftId { get; set; }
        [Required(ErrorMessage = "Please add the aircraft name.")]

        public string Name { get; set; } = string.Empty;
        [Required(ErrorMessage = "Please add the aircraft type.")]

        public string Type {  get; set; } = string.Empty;
        [Required(ErrorMessage = "Please add the aircraft capacity.")]

        public int Capacity { get; set; }
    }
}

AirportTracker/Controllers/AircraftController.cs
using Microsoft.AspNetCore.Mvc;
using AirportTracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace AirportTracker.Controllers
{
    public class AircraftController : BaseController
    {
        public AircraftController(AirportContext ctx) : base(ctx)
        {

        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult ListAircraft()
        {
            try
            {
                var aircraft = Context.Aircrafts.ToList();
                return View(aircraft);
            }
            catch(Exception ex)
            {
                Console.WriteLine($"List Aircraft Failed: {ex.Message}");
                return RedirectToAction("Flight", "Index");
            }
            
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddAircraft()
        {
            try
            {
                return View(new Aircraft());
            }
            catch(Exception ex)
            {
                Console.WriteLine($"Add Aircraft Get Failed: {ex.Message}");
                return RedirectToAction("ListAircraft");
            }
            
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddAircraft(Aircraft aircraft)
        {
            try
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                ViewBag.Errors = errors;

                if (ModelState.IsValid)
                {
                    Context.Aircrafts.Add(aircraft);
                    Context.SaveChanges();
                    return RedirectToAction("ListAircraft", "aircraft");
                }
                return View(aircraft);
            }
            catch(Exception ex)
            {
                Console.WriteLine($"Add Aircraft Post Failed: {ex.Message}");
                return View(aircraft);
            }
            
        }
    }
}

AirportTracker/Views/Aircraft/AddAircraft.cshtml
@model Aircraft
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>This is the add aircraft page</p>

<form asp-action="AddAircraft" method="post">
    <input type="hidden" asp-for="AircraftId"/>

    <div>
        <label asp-for="Name" class="form-label">Name of Aircraft</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Type" class="form-label">Type of Aircraft</label>
        <input asp-for="Type" class="form-control" />
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Capacity" class="form-label">Capacity</label>
        <input asp-for="Capacity" class="form-control" />
        <span asp-validation-for="Capacity" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <a asp-action="ListAircraft" class="btn btn-primary">Cancel</a>
</form>

AirportTracker/Views/Aircraft/ListAircraft.cshtml
@model List<Aircraft>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>This is the list aircraft page</p>
<a asp-action="AddAircraft" asp-controller="Aircraft">Add Aircraft</a>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Aircraft Name</th>
            <th>Aircraft Type</th>
            <th>Aircraft Capacity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var aircraft in Model)
        {
            <tr>
                <td>@aircraft.Name</td>
                <td>@aircraft.Type</td>
                <td>@aircraft.Capacity</td>
            </tr>
        }

    </tbody>
</table>