AirportTracker/Models/Flight.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AirportTracker.Models
{
    public class Flight
    {
        public int FlightId { get; set; }
        [Required(ErrorMessage = "Price is Required")]
        [Range(1, 3000)]
        public double FlightPrice { get; set; }
        [Required(ErrorMessage = "Takeoff is Required")]
        public DateTime TakeOff { get; set; }

        [Required(ErrorMessage = "Please include passenger total")]
        [Range(1, Int32.MaxValue)]
        public int PassengerTotal { get; set; }
        public int? PassengerCount { get; set; }
        //Might not add to database, if it doesn't, just add in the post for the method that updates passenger count. passengerCount.PassengerCount++.
        public void AddPassengerCount()
        {
            PassengerCount++;
        }
        [NotMapped]
        public string DisplayLocation => $"{DepartureAirport} to {ArrivalAirport}";

        public Airport? Airport { get; set; }
        [ForeignKey("DepartureAirport")]
        [Required(ErrorMessage = "Departure Airport is Required")]
        public int DepartureAirportId { get; set; }
        public string DepartureAirport { get; set; } = string.Empty;
        [ForeignKey("ArrivalAirport")]
        [Required(ErrorMessage = "Arrival Airport is Required")]
        public int ArrivalAirportId { get; set; }
        public string ArrivalAirport { get; set; } = string.Empty;
        
        public Employee? Employee { get; set; }
        public Aircraft? Aircraft { get; set; }
        [ForeignKey("AircraftId")]
        [Required(ErrorMessage = "Aircraft is Required")]
        public int AircraftId {  get; set; }

        public Terminal? Terminal { get; set; }
        [ForeignKey("TerminalId")]
        [Required(ErrorMessage = "Terminal is Required")]
        public int TerminalId { get; set; }
    }
}

AirportTracker/Models/MyBookingsViewModel.cs
namespace AirportTracker.Models
{
    public class MyBookingsViewModel
    {
        public IEnumerable<Booking> UpcomingFlights { get; set; }
        public IEnumerable<Booking> PriorFlights { get; set; }
    }
}

AirportTracker/Controllers/FlightController.cs
using AirportTracker.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AirportTracker.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class FlightController : BaseController
    {

        public FlightController(AirportContext ctx) : base(ctx) { }

        public IActionResult Index()
        {
            try
            {
                var userId = User.Identity?.GetUserId();
                var nextFlight = GetNextBookedFlight(userId);
                if (nextFlight != null && nextFlight.TakeOff > DateTime.Now)
                {
                    ViewBag.NextFlightNotification = $"Your next flight is to {nextFlight.DisplayLocation} on {nextFlight.TakeOff.ToShortDateString()}";
                }
                List<Flight> flight = setFlightData();

                return View(flight);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Index Failed To Get: {ex.Message}");
                return RedirectToAction("Index", "Home");
            }

        }

        public Flight GetNextBookedFlight(string userId)
        {
            try
            {
                var currentDate = DateTime.Now.AddHours(24);
                var nextFlight = (from b in Context.Bookings
                                  join f in Context.Flights on b.FlightId equals f.FlightId
                                  where b.UserId == userId && f.TakeOff < currentDate
                                  orderby f.TakeOff
                                  select f).FirstOrDefault();
                return nextFlight;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Get Next Booked Flight Failed: {ex.Message}");
                return null;
            }
        }
        public List<Flight> setFlightData()
        {
            try
            {
                List<Airport> Airports = new List<Airport>();
                List<Terminal> Terminals = new List<Terminal>();
                IQueryable<Airport> Aquery = Context.Airports.OrderBy(e => e.AirportId);
                foreach (Airport e in Aquery)
                { Airports.Add(e); }
                ViewBag.Airports = Airports;
                List<Flight> flight = Context.Flights.OrderBy(e => e.AircraftId).Include(t => t.Terminal).ToList();
                List<Terminal> terminal = Context.Terminals.OrderBy(t => t.TerminalId).ToList();
                List<Aircraft> aircrafts = new List<Aircraft>();
                IQueryable<Aircraft> aquery = Context.Aircrafts.OrderBy(e => e.AircraftId);

                foreach (Aircraft air in aquery)
                {
                    aircrafts.Add(air);
                }
                ViewBag.Aircrafts = aircrafts;
                return flight;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Set Flight Data Failed: {ex.Message}");
                return null;
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult AddFlight()
        {
            try
            {
                List<Airport> Airports = new List<Airport>();
                IQueryable<Airport> Aquery = Context.Airports.OrderBy(e => e.AirportId);
                foreach (Airport e in Aquery)
                { Airports.Add(e); }
                ViewBag.Airports = Airports;
                List<Aircraft> aircrafts = new List<Aircraft>();
                IQueryable<Aircraft> aquery = Context.Aircrafts.OrderBy(e => e.AircraftId);

                foreach (Aircraft air in aquery)
                {
                    aircrafts.Add(air);
                }
                ViewBag.Aircrafts = aircrafts;

                List<Terminal> Terminals = new List<Terminal>();
                IQueryable<Terminal> tquery = Context.Terminals.OrderBy(e => e.TerminalId);
                foreach (Terminal t in tquery)
                {
                    Terminals.Add(t);
                }
                ViewBag.Terminals = Terminals;
                return View(new Flight());
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Add Flight Failed To Get");
                return View("Index");
            }

        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddFlight(Flight flight)
        {
            try
            {
                List<Airport> Airports = new List<Airport>();
                IQueryable<Airport> Aquery = Context.Airports.OrderBy(e => e.AirportId);
                foreach (Airport e in Aquery)
                { Airports.Add(e); }
                ViewBag.Airports = Airports;
                List<Aircraft> aircrafts = new List<Aircraft>();
                IQueryable<Aircraft> aquery = Context.Aircrafts.OrderBy(e => e.AircraftId);

                foreach (Aircraft air in aquery)
                {
                    aircrafts.Add(air);
                }
                ViewBag.Aircrafts = aircrafts;
                List<Terminal> Terminals = new List<Terminal>();
                IQueryable<Terminal> tquery = Context.Terminals.OrderBy(e => e.TerminalId);
                foreach (Terminal t in tquery)
                {
                    Terminals.Add(t);
                }
                ViewBag.Terminals = Terminals;
                if (ModelState.IsValid)
                {
                    if (flight.PassengerTotal <= aircrafts.Find(e => e.AircraftId == flight.AircraftId).Capacity) 
                    {
                        var departureAirport = Context.Airports
                            .FirstOrDefault(a => a.AirportId == flight.DepartureAirportId)?.Name;
                        var arrivalAirport = Context.Airports
                            .FirstOrDefault(a => a.AirportId == flight.ArrivalAirportId)?.Name;

                        if (departureAirport != null)
                        {
                            flight.DepartureAirport = departureAirport;
                        }

                        if (arrivalAirport != null)
                        {
                            flight.ArrivalAirport = arrivalAirport;
                        }
                        flight.PassengerCount = 0;
                        Context.Flights.Add(flight);
                        await Context.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                }
                
                return View(flight);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Add Airport Failed To Post: {ex.Message}");
                return View(flight);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> EditFlight(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    List<Airport> Airports = new List<Airport>();
                    IQueryable<Airport> Aquery = Context.Airports.OrderBy(e => e.AirportId);
                    foreach (Airport e in Aquery)
                    { Airports.Add(e); }
                    ViewBag.Airports = Airports;
                    List<Aircraft> aircrafts = new List<Aircraft>();
                    Flight currentFlight = new Flight();
                    IQueryable<Aircraft> aquery = Context.Aircrafts.OrderBy(e => e.AircraftId);
                    List<Flight> flights = Context.Flights.OrderBy(e => e.AircraftId).ToList();
                    foreach (Aircraft air in aquery)
                    {
                        aircrafts.Add(air);
                    }
                    ViewBag.Aircrafts = aircrafts;
                    foreach (Flight newFlight in flights)
                    {
                        if (newFlight.FlightId == id)
                        {
                            currentFlight = newFlight;
                        }
                    }

                    return View(currentFlight);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Edit Flight Failed To Get: {ex.Message}");
                return View("Index");
            }

        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> EditFlight(Flight currentFlight)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Context.Flights.Update(currentFlight);
                    await Context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    Console.WriteLine($"Edit Flight Failed To Post: {ex.Message}");
                }
            }
            return View(currentFlight);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                List<Airport> Airports = new List<Airport>();
                IQueryable<Airport> Aquery = Context.Airports.OrderBy(e => e.AirportId);
                foreach (Airport e in Aquery)
                { Airports.Add(e); }
                ViewBag.Airports = Airports;
                var flight = await Context.Flights.FirstOrDefaultAsync(m => m.FlightId == id);
                if (flight == null)
                {
                    return NotFound();
                }
                return View(flight);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Delete Flight Failed To Get: {ex.Message}");

AirportTracker/Views/Flight/AddFlight.cshtml
@model Flight

<h2>Add A Flight</h2>

<form asp-action="AddFlight" asp-controller="Flight" method="post">
    <input type="hidden" asp-for="FlightId"/>
    <div>
        <label asp-for="FlightPrice" class="form-label">Flight Price</label>
        <input asp-for="FlightPrice" class="form-control" />
        <span asp-validation-for="FlightPrice" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="TakeOff" class="form-label">Take off time</label>
0        <input asp-for="TakeOff" type="time"  class="form-control" />
        <span asp-validation-for="TakeOff" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="PassengerTotal" class="form-label">Passenger total</label>
        <input asp-for="PassengerTotal" class="form-control" />
        <span asp-validation-for="PassengerTotal" class="text-danger"></span>
    </div>
    <div>
        <select id="@Model.TerminalId" name="terminalId" class="form-select" required>
            <option value="">--Select A Terminal--</option>
            @foreach(var terminal in ViewBag.Terminals){
                <option value="@terminal.TerminalId">@terminal.TerminalName</option>
            }
        </select>
        <span asp-validation-for="TerminalId" class="text-danger"></span>
    </div>
    <br />
    <div>
        <select id="@Model.AircraftId" name="aircraftId" class="form-select" required>
        <option value="">--Select Aircraft--</option>
        @foreach (var aircraft in ViewBag.Aircrafts)
        {
            <option value="@aircraft.AircraftId">@aircraft.Name</option>
        }
        </select>
        <span asp-validation-for="AircraftId" class="text-danger"></span>
    </div>
    <br />
    <div>
        <select id="@Model.DepartureAirportId" name="departureAirportId" class="form-select" required>
            <option value="">--Select Depart Airport--</option>
            @foreach (var airport in ViewBag.Airports)
            {
                <option value="@airport.AirportId">@airport.Name</option>
            }
        </select>
        <span asp-validation-for="DepartureAirportId" class="text-danger"></span>
    </div>
    <br />
    <div>
        <select id="@Model.ArrivalAirportId" name="arrivalAirportId" class="form-select" required>
            <option value="">--Select Arrival Airport--</option>
            @foreach (var airport in ViewBag.Airports)
            {
                <option value="@airport.AirportId">@airport.Name</option>
            }
        </select>
        <span asp-validation-for="ArrivalAirportId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

AirportTracker/Views/Flight/BookFlight.cshtml
@model Booking

<p>This is the book flight page</p>

<form asp-action="BookFlight" method="post">
    <div>
        <label class="form-label">Selected Flight</label>
        <p>Flight ID: @ViewBag.Flight.FlightId - @ViewBag.Flight.DisplayLocation</p>
        <input type="hidden" asp-for="FlightId" />
    </div>

    <br />

    <div>
        <label asp-for="NumberOfSeats" class="form-label">Number of Seats</label>
        <input asp-for="NumberOfSeats" type="number" min="1" class="form-control" required />
        <span asp-validation-for="NumberOfSeats" class="text-danger"></span>
    </div>

    <br />

    <button type="submit" class="btn btn-primary">Book Flight</button>
</form>

AirportTracker/Views/Flight/BookingConfirmation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Booking

<h2>Booking Confirmation</h2>

<p>Your booking is confirmed.</p>
<p>Flight: @Model.Flight.DisplayLocation</p>
<p>Number of Seats: @Model.NumberOfSeats</p>
<p>Booking Date: @Model.BookingDate</p>
<a asp-controller="Flight" asp-action="Index" class="btn btn-primary">Return To Flights</a>
<a asp-controller="Flight" asp-action="MyBookings" class="btn btn-primary"> Proceed To My Bookings</a>

AirportTracker/Views/Flight/CancelBooking.cshtml
@model Booking
<h2>Cancel Booking</h2>

<form asp-action="ConfirmCancelBooking" method="post">
    <input type="hidden" asp-for="BookingId" />
    <h2>@Model.Flight.DisplayLocation, @Model.BookingDate</h2>
    <h2>@Model.NumberOfSeats, @Model.Flight.FlightPrice.ToString("C2")</h2>

    <button type="submit" class="btn btn-primary">Cancel Flight</button>
    <a asp-action="MyBookings" class="btn btn-primary">Return To My Bookings</a>
</form>

AirportTracker/Views/Flight/Delete.cshtml
@model Flight

@{
    var currentDepartAirport = "";
    if (ViewBag.Airports != null)
    {
        foreach (var airport in ViewBag.Airports)
        {
            if (airport.AirportId == Model.DepartureAirportId)
            {
                currentDepartAirport = airport.Name;
            }
        }
    }
    var currentArrivalAirport = "";
    if (ViewBag.Airports != null)
    {
        foreach (var airport in ViewBag.Airports)
        {
            if (airport.AirportId == Model.ArrivalAirportId)
            {
                currentArrivalAirport = airport.Name;
            }
        }
    }
}
<h1> Do you wish to delist the flight from @currentDepartAirport to @currentArrivalAirport?</h1>
<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="FlightId"/>
    <input type="submit" value="Delete" class="btn btn-danger" />
    <a asp-action="Index">Back to flight list</a>
</form>

AirportTracker/Views/Flight/EditFlight.cshtml
@model Flight
@{
    var currentAircraft = "";
    if (ViewBag.Aircrafts != null)
    {
        foreach(var aircraft in ViewBag.Aircrafts)
        {
            if (aircraft.AircraftId == Model.AircraftId)
            {
                currentAircraft = aircraft.Name;
            }
        }
    }
    var currentDepartAirport = "";
    if (ViewBag.Airports != null)
    {
        foreach (var airport in ViewBag.Airports)
        {
            if (airport.AirportId == Model.DepartureAirportId)
            {
                currentDepartAirport = airport.Name;
            }
        }
    }
    var currentArrivalAirport = "";
    if (ViewBag.Airports != null)
    {
        foreach (var airport in ViewBag.Airports)
        {
            if (airport.AirportId == Model.ArrivalAirportId)
            {
                currentArrivalAirport = airport.Name;
            }
        }
    }
}
<form asp-action="EditFlight" asp-controller="Flight" method="post">
    <input type="hidden" asp-for="FlightId" />
    <div class="form-group">
        <label asp-for="FlightPrice" class="form-label"></label>
        <input asp-for="FlightPrice" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PassengerTotal" class="form-label"></label>
        <input asp-for="PassengerTotal" class="form-control" />
    </div>
    <div>
        <label asp-for="TakeOff" class="form-label">Take off time</label>
        <input asp-for="TakeOff" type="time" class="form-control" />
    </div>
    <br />
    <div class="form-group">
        <label for="@Model.AircraftId" class="form-label">Select Aircraft</label>
        <select id="@Model.AircraftId" name="aircraftId" class="form-select" required>
            <option value="@Model.AircraftId">@currentAircraft</option>
            @if(ViewBag.Aircrafts != null)
            {
                foreach(var aircraft in ViewBag.Aircrafts)
                {
                    if(aircraft.Name != currentAircraft)
                    {
                        <option value="@aircraft.AircraftId">@aircraft.Name</option>
                    }
                }
            }
        </select>
    </div>
    <br />
    <div class="form-group">
        <label for="@Model.DepartureAirportId" class="form-label">Select Aircraft</label>
        <select id="@Model.DepartureAirportId" name="departureAirportId" class="form-select" required>
            <option value="@Model.DepartureAirportId">@currentDepartAirport</option>
            @if (ViewBag.Airports != null)
            {
                foreach (var airport in ViewBag.Airports)
                {
                    if (airport.Name != currentDepartAirport)
                    {
                        <option value="@airport.AirportId">@airport.Name</option>
                    }
                }
            }
        </select>
    </div>
    <br />
    <div class="form-group">
        <label for="@Model.ArrivalAirportId" class="form-label">Select Aircraft</label>
        <select id="@Model.ArrivalAirportId" name="arrivalAirportId" class="form-select" required>
            <option value="@Model.ArrivalAirportId">@currentArrivalAirport</option>
            @if (ViewBag.Airports != null)
            {
                foreach (var airport in ViewBag.Airports)
                {
                    if (airport.Name != currentArrivalAirport)
                    {
                        <option value="@airport.AirportId">@airport.Name</option>
                    }
                }
            }
        </select>
    </div>
    <a asp-action="Index">Back to Index</a>
    <button type="submit" value="Save" class="btn btn-primary">Submit</button>
</form>

AirportTracker/Views/Flight/Index.cshtml
@model List<Flight>
@{
    var currentAircraft = "";
    var currentDepartAirport = "";
    var currentArrivalAirport = "";
    var currentDepartState = "";
    var currentArrivalState = "";

    if(ViewBag.FilterType == null)
    {
        ViewBag.FilterType = "Id";
    }

}
<h2>Upcoming Flights</h2>
@if (ViewBag.NextFlightNotification != null)
{
    <div class="alert alert-info">
        <strong>Notification:</strong> @ViewBag.NextFlightNotification
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div>
    <button type="button" class="btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#filterTypeModal">
        <span class="fas fa-edit"></span>&nbsp;Change Filter Type
    </button>
    <div class="modal fade" id="filterTypeModal" tabindex="-1" aria-labelledby="filterTypeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="filterTypeModalLabel">Change Filter Type</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form asp-action="filterType" asp-controller="Flight" method="post">
                    <select id="@ViewBag.FilterType" name="filterType" class="form-slect">
                        <option id="Id" value="Id">Flight Id</option>
                        <option id="DepartureState" value="DepartureState">Flight Departure Airport</option>
                        <option id="ArrivalState" value="ArrivalState"> Flight Arrival Airport</option>
                        </select>
                        <button type="submit" class="btn btn-primary">Change Filter</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
<div id="inputBox">
    <form asp-action="FilterData" asp-controller="Flight">
        <input type="text" name="SearchString" id="inputBox" />
        <input type="hidden" name="filterType" value="@ViewBag.FilterType" />
        <input type="submit" class="button" value="Filter" class="btn btn-primary" />
    </form>
</div>
<div>

<div class="listContainer">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Departure Airport</th>
                <th>Arrival Airport</th>
                <th>Flight Price</th>
                <th>Terminal Number</th>
                <th>Flight Starting Location</th>
                <th>Flight Ending Location</th>
                <th>Flight Passenger Capacity</th>
                <th>Remaining Seats</th>
                <th>Flight Take off time</th>
                <th>Flight Aircraft</th>

                @if (User.IsInRole("Admin"))
                {
                <th></th>
                <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach(var flight in Model)
            {
                <tr>
                        <td>
                            @if (ViewBag.Airports != null)
                            {
                                foreach (var airport in ViewBag.Airports)
                                {
                                    if (airport.AirportId == flight.DepartureAirportId)
                                    {
                                        currentDepartAirport = airport.Name;
                                    }
                                }
                            }
                            @currentDepartAirport
                        </td>
                        <td>
                            @if (ViewBag.Airports != null)
                            {
                                foreach (var airport in ViewBag.Airports)
                                {
                                    if (airport.AirportId == flight.ArrivalAirportId)
                                    {
                                        currentArrivalAirport = airport.Name;
                                    }
                                }
                            }
                            @currentArrivalAirport
                        </td>
                    <td>@flight.FlightPrice</td>
                    <td>@flight.Terminal?.TerminalName</td>
                    <td>
                        @if (ViewBag.Airports != null)
                        {
                            foreach (var airport in ViewBag.Airports)
                            {
                                if (airport.AirportId == flight.DepartureAirportId)
                                {
                                    currentDepartState = airport.City + ", " + airport.State;
                                }
                            }
                        }
                        @currentDepartState
                    </td>
                    <td>
                        @if (ViewBag.Airports != null)
                        {
                            foreach (var airport in ViewBag.Airports)
                            {
                                if (airport.AirportId == flight.ArrivalAirportId)
                                {
                                    currentArrivalState = airport.City + ", " + airport.State;
                                }
                            }
                        }
                        @currentArrivalState
                    </td>
                        <td>@flight.PassengerTotal</td>
                    <td>@(@flight.PassengerTotal - @flight.PassengerCount)</td>
                    <td>@flight.TakeOff</td>
                    <td>
                        @if (ViewBag.Aircrafts != null)
                        {
                            foreach (var aircrafts in ViewBag.Aircrafts)
                            {
                                if (aircrafts.AircraftId == flight.AircraftId)
                                {
                                    currentAircraft = aircrafts.Name;
                                }
                            }
                        }
                        @currentAircraft
                    </td>
                    
                    @if (User.IsInRole("Admin"))
                    {
                        <td>
                            <div>
                                <a asp-action="EditFlight" asp-controller="Flight" asp-route-id="@flight.FlightId" class="accordion-button">
                                    Edit
                                </a>
                            </div>
                        </td>
                        <td>
                            <div>
                                <a asp-action="Delete" asp-controller="Flight" asp-route-id="@flight.FlightId" class="accordion-button" method="get">
                                    Delete
                                </a>
                            </div>
                        </td>
                    }
                    <td>
                        @if(User.Identity.IsAuthenticated || User.IsInRole("Admin"))
                        {
                                <div>
                                    <a asp-action="BookFlight" asp-controller="Flight" asp-route-flightId="@flight.FlightId">Book Flight</a>
                                </div>
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
</div>

AirportTracker/Views/Flight/MyBookings.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MyBookingsViewModel

<h2>My Bookings</h2>
@if(Model.UpcomingFlights.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Booking ID</th>
                <th>Flight</th>
                <th>Price</th>
                <th>Number of Seats</th>
                <th>Booking Date</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach(var booking in Model.UpcomingFlights)
            {
                <tr>
                    <td>@booking.BookingId</td>
                    <td>@booking.Flight?.DisplayLocation</td>
                    <td>@booking.Flight.FlightPrice</td>
                    <td>@booking.NumberOfSeats</td>
                    <td>@booking.BookingDate.ToString("MM/dd/yyyy")</td>
                    <td><a asp-action="CancelBooking" asp-controller="Flight" asp-route-id="@booking.BookingId">Cancel Flight</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>You have no bookings yet.</p>
}


@if (Model.PriorFlights.Any())
{
    <h2>Prior Bookings</h2>
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Booking ID</th>
                    <th>Flight</th>
                    <th>Number of Seats</th>
                    <th>Booking Date</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var booking in Model.PriorFlights)
                {
                    <tr>
                        <td>@booking.BookingId</td>
                        <td>@booking.Flight?.DisplayLocation</td>
                        <td>@booking.NumberOfSeats</td>
                        <td>@booking.BookingDate.ToString("MM/dd/yyyy")</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

<a asp-action="Index" asp-controller="Flight" class="btn btn-primary">Return To Flights</a>